### ISSUE TITLE
Incompatible OSGi core library included in WAR file

### ISSUE THREAD

**Issue by rwi** [Communote/communote-server#12]
The library org.osgi:org.osgi.core:4.3.1 is added to WEB-INF/lib which conflicts with the used Felix framework because the Felix version 4.2.1 provides and uses an (incomplete) OSGi core implementation of specification version 5. So in case the classloader first checks the separate OSGi library the start can fail with the following exception:

```
2016-07-26 16:46:05,581 No Client ERROR localhost-startStop-1 org.springframework.web.context.ContextLoader - Context initialization failed
java.lang.NoSuchMethodError: org.osgi.framework.wiring.BundleWire.getProvider()Lorg/osgi/framework/wiring/BundleRevision;
	at org.apache.felix.framework.BundleRevisionDependencies.addDependent(BundleRevisionDependencies.java:44)
	at org.apache.felix.framework.StatefulResolver.markResolvedRevisions(StatefulResolver.java:998)
	at org.apache.felix.framework.StatefulResolver.resolve(StatefulResolver.java:427)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3967)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1247)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1219)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:508)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.start(DirectoryWatcher.java:224)
	at org.apache.felix.fileinstall.internal.FileInstall.updated(FileInstall.java:252)
	at com.communote.server.core.osgi.OSGiManagement.start(OSGiManagement.java:357)
	at com.communote.server.core.osgi.OSGiManagement.initializationComplete(OSGiManagement.java:197)
	at com.communote.server.core.bootstrap.ApplicationInitializer.completeInitialization(ApplicationInitializer.java:193)
	at com.communote.server.core.bootstrap.ApplicationInitializer.fulfillInitializationCondition(ApplicationInitializer.java:235)
	at com.communote.server.core.application.DefaultRuntime.fulfillInitializationCondition(DefaultRuntime.java:58)
	at com.communote.server.web.bootstrap.WebAppReadyListener.onApplicationEvent(WebAppReadyListener.java:27)
	at com.communote.server.web.bootstrap.WebAppReadyListener.onApplicationEvent(WebAppReadyListener.java:16)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(Unknown Source)
	at org.apache.catalina.core.StandardContext.startInternal(Unknown Source)
	at org.apache.catalina.util.LifecycleBase.start(Unknown Source)
	at org.apache.catalina.core.ContainerBase.addChildInternal(Unknown Source)
	at org.apache.catalina.core.ContainerBase.addChild(Unknown Source)
	at org.apache.catalina.core.StandardHost.addChild(Unknown Source)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(Unknown Source)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-07-26 16:46:05,595 No Client INFO localhost-startStop-1 com.communote.server.web.bootstrap.WebAppShutdownListener - Stopping Communote
```

**Comment by rwi** [comment]
The OSGi core was pulled in by Restlet.
